config/routes.rb
Rails.application.routes.draw do
  resources :restaurants
  resources :teams
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :members
  root 'home#index'
  get 'home/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  post 'home/pick_restaurant', to: 'home#pick_restaurant'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def pick_restaurant
    @restaurant = Restaurant.order("RANDOM()").first
    render json: @restaurant
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <% if current_user %>
    <% if current_user.team %>
      <%= link_to current_user.team.teamName, root_path, class:"navbar-brand" %>
    <% else %>
      <%= link_to 'Your Team Name', new_team_path, class:"navbar-brand" %>
    <% end %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item mr-2">
        <%= link_to 'About', home_about_path, class:"nav-link" %>
      </li>

    <% if user_signed_in? %>

        <li class="nav-item mr-2">
         <%= link_to 'Members', members_path, class:"nav-link" %>
        </li>

        <li class="nav-item mr-2">
          <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link" %>
        </li>

      <li class="nav-item mr-2">
       <% if current_user.team %>
        <%= link_to 'Team', team_path(current_user.team), class: "nav-link" %>
       <% else %>
        <%= link_to 'Create Team', new_team_path, class: "nav-link" %> <!-- Assuming you want to offer a way to create a team -->
       <% end %>
      </li>

      <li class="nav-item mr-2">
        <%= link_to 'Restaurants', restaurants_path, class:"nav-link" %>
      </li>
   

      <li class="nav-item mr-2">
        <%= link_to 'Sign-out', destroy_user_session_path, data: {turbo_method: :delete}, class:"nav-link" %>
      </li>

    <% else %>
        <li class="nav-item mr-2">
            <%= link_to 'Sign-up', new_user_registration_path, class:"nav-link" %>
        </li>

        <li class="nav-item mr-2">
            <%= link_to 'Sign-in', new_user_session_path, class:"nav-link" %>
        </li>

    <% end %>




    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About</h1>

<p>
Thank you for dropping by. It has been a wonderful four months so far. Big big thanks to the whole team. It is a great honor working with you amazing people. This app is a gift project (sort of?) that is designed to solve one tiny problem I had in my life and the team had daily: what to have for lunch?
It is always very hard to come up with options and to choose from these. Moreover, there are many restaurants near the office we have never been to, probably because we do not even know they exist. Anyways, you can use this tool if you cannot make a decision, or you simply want to let the goddess of randomness decide your fate. Hope that will be fun. 
</p>

<br />

<p>
Of course, the project is far far far away from its ideal stage.
</p>

<p>1. The UI design is minimal (no design at all)</p>
<p>2. The recommendation algorithm is incomplete</p>
<p>3. The restaurants are manually input. </p>
<p>Ideally, it should have</p>
<p>1. A better design</p>
<p>2. A stronger recommendation algorithm (you have a higher chance to get healthy food if your team members healthy score is higher)</p>
<p>3. A dynamically generated restaurant list (you should be able to have a list of open restaurants near you whereever you are; this can probably be achieve by talking to the Google Map API)</p>

<p>Anyways, since it is fun to work on this project and I have more spare time this June, I will keep working on this project. Stay tuned LOL.</p>

app/views/home/index.html.erb
<h1>Welcome to Lunch Selector</h1>

<button id="pickRestaurantButton">Pick a Restaurant</button>
<p id="pickedRestaurant"></p>

<script>
        document.getElementById('pickRestaurantButton').addEventListener('click', function() {
        fetch('/home/pick_restaurant', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'X-CSRF-Token': document.querySelector('meta[name="csrf-token"]').getAttribute('content')
        },
        })
        .then(response => response.json())
        .then(data => {
        document.getElementById('pickedRestaurant').textContent = `Picked Restaurant: ${data.title}`;
        })
        .catch((error) => {
        console.error('Error:', error);
        });
    });
    </script>
<% if current_user == nil %>
    <p>To access full content,please sign in first</p>
    <%= link_to "Sign-in", new_user_session_path, class:"btn, btn-secondary"%>
<% end %>