config/routes.rb
Rails.application.routes.draw do
  resources :restaurants
  resources :teams
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :members
  root 'home#index'
  get 'home/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  post 'home/pick_restaurant', to: 'home#pick_restaurant'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/member.rb
class Member < ApplicationRecord
    belongs_to :team
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [ :show, :edit, :update, :destroy ]
  # If you are not the user who creates the member, you are not authorized to edit it.
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /members or /members.json
  def index
    if current_user
      if current_user.team
        @members = current_user.team.members
      end
    else
      redirect_to new_user_registration_path, notice:"Register First"
    end
  end

  # GET /members/1 or /members/1.json
  def show
  end

  # GET /members/new
  def new
    if current_user.team
      @member = current_user.team.members.new
    else
      redirect_to new_team_path, notice:"You must be part of a team"
    end
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members or /members.json
  def create
    if current_user.team
      @member = current_user.team.members.build(member_params)

      respond_to do |format|
        if @member.save
          format.html { redirect_to member_url(@member), notice: "Member was successfully created." }
          format.json { render :show, status: :created, location: @member }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @member.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to new_team_path, notice: "You must be part of a team to create members."
    end
  end

  # PATCH/PUT /members/1 or /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to member_url(@member), notice: "Member was successfully updated." }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1 or /members/1.json
  def destroy
    @member.destroy!

    respond_to do |format|
      format.html { redirect_to members_url, notice: "Member was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @member = current_user.team.members.find_by(id: params[:id])
    redirect_to members_path, notice: "Not Authorized to Edit This Member" if @member.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = current_user.team.members.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def member_params
      params.require(:member).permit(:first_name, :last_name, :spicy, :healthy, :team_id)
    end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= form_with(model: member) do |form| %>
  <% if member.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
        <% member.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name, class:"form-control", placeholder:"AK" %>
  </div>

  <div class="field form-group">
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name, class:"form-control", placeholder:"Kai" %>
  </div>
      
  <div class="field form-group slider-container">
    <%= form.label :spicy, "Acceptance to Spicy Food", class: "form-label" %>
    <%= form.range_field :spicy, min: 0, max: 5, step: 0.5, value: member.spicy || 2.5, id: "customRange3", class:"form-range"%>
    <span class="slider-value"><%= member.spicy %></span>
  </div>

  <div class="field form-group slider-container">
    <%= form.label :spicy, "How healthy do you want", class: "form-label" %>
    <%= form.range_field :healthy, min: 0, max: 5, step: 0.5, value: member.healthy || 2.5, id: "customRange3", class:"form-range"%>
    <span class="slider-value"><%= member.healthy %></span>
  </div>

  <div class="action">
    <%= form.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing member</h1>

<br>

<%= render "form", member: @member %>

<br>

<div>
  <%= link_to "Show this member", @member, class:"btn btn-secondary" %> |
  <%= link_to "Back to members", members_path, class:"btn btn-secondary" %>
</div>

app/views/members/index.html.erb
<table class="table table-striped table-bordered table-hover">
  <thread class="thread-dark">
    <tr>
      <th>Name</th>
      <th>Spicy</th>
      <th>Healthy</th>
    </tr>
  </thread>


  <tbody>
    <% if @members != nil %>
      <% @members.each do |member| %>
        <tr>
          <td><%= link_to member.first_name + ' ' + member.last_name, member %></td>
          <td><%= member.spicy %></td>
          <td><%= member.healthy %></td>
          <td><%= link_to 'Delete', member_path(member), data: { turbo_method: :delete, turbo_confirm: 'Are you sure' } , class: "btn btn-outline-danger btn-sm" %></td>

        </tr>
     <% end %>

    <% end %>

  </tbody>

</table>


<%= link_to "New member", new_member_path, class:"btn btn-secondary" %>

app/views/members/new.html.erb
<h1> Add New member</h1>

<%= render "form", member: @member %>


<br>

<div>
  <%= link_to "Back to members", members_path, class:"btn btn-dark"%>
</div>

app/views/members/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">Hello <%= @member.first_name%> </h1>
  <p><%= @member.spicy%> | <%= @member.healthy%></p>
  <hr class="my-4">
  <%= link_to "Edit this member", edit_member_path(@member), class:"btn btn-secondary" %> |
  <%= link_to "Back to members", members_path, class:"btn btn-secondary" %>

  <br></br>
  <%= button_to "Destroy this member", @member, data: {turbo_method: :delete} %>

</div>